"""Initial database schema

Revision ID: 0c15cb35abb0
Revises: 
Create Date: 2025-11-14 03:51:03.353175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c15cb35abb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('last_scanned', sa.DateTime(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('scan_depth', sa.Integer(), nullable=True),
    sa.Column('exclude_patterns', sa.String(), nullable=True),
    sa.Column('scan_status', sa.String(), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=True),
    sa.Column('total_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['directories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directories_id'), 'directories', ['id'], unique=False)
    op.create_index(op.f('ix_directories_name'), 'directories', ['name'], unique=False)
    op.create_index(op.f('ix_directories_path'), 'directories', ['path'], unique=True)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.String(), nullable=False),
    sa.Column('query_type', sa.String(), nullable=True),
    sa.Column('query_embedding', sa.String(), nullable=True),
    sa.Column('filters_json', sa.Text(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('search_mode', sa.String(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('search_time_ms', sa.Integer(), nullable=True),
    sa.Column('results_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_history_id'), 'search_history', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_query_text'), 'search_history', ['query_text'], unique=False)
    op.create_index(op.f('ix_search_history_query_type'), 'search_history', ['query_type'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('is_system_tag', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_category'), 'tags', ['category'], unique=False)
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_category'), 'user_settings', ['category'], unique=False)
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_settings_key'), 'user_settings', ['key'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('text_vector', sa.String(), nullable=True),
    sa.Column('image_tags', sa.Text(), nullable=True),
    sa.Column('audio_transcript', sa.Text(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('search_score', sa.Float(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('directory_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_status', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['directory_id'], ['directories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_content_type_created', 'files', ['content_type', 'created_at'], unique=False)
    op.create_index('idx_files_directory_filename', 'files', ['directory_id', 'filename'], unique=False)
    op.create_index('idx_files_extension_size', 'files', ['extension', 'size'], unique=False)
    op.create_index('idx_files_search_score', 'files', ['search_score'], unique=False)
    op.create_index(op.f('ix_files_content_hash'), 'files', ['content_hash'], unique=False)
    op.create_index(op.f('ix_files_content_type'), 'files', ['content_type'], unique=False)
    op.create_index(op.f('ix_files_extension'), 'files', ['extension'], unique=False)
    op.create_index(op.f('ix_files_filename'), 'files', ['filename'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_mime_type'), 'files', ['mime_type'], unique=False)
    op.create_index(op.f('ix_files_path'), 'files', ['path'], unique=True)
    op.create_table('file_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_tags_id'), 'file_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_tags_id'), table_name='file_tags')
    op.drop_table('file_tags')
    op.drop_index(op.f('ix_files_path'), table_name='files')
    op.drop_index(op.f('ix_files_mime_type'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_filename'), table_name='files')
    op.drop_index(op.f('ix_files_extension'), table_name='files')
    op.drop_index(op.f('ix_files_content_type'), table_name='files')
    op.drop_index(op.f('ix_files_content_hash'), table_name='files')
    op.drop_index('idx_files_search_score', table_name='files')
    op.drop_index('idx_files_extension_size', table_name='files')
    op.drop_index('idx_files_directory_filename', table_name='files')
    op.drop_index('idx_files_content_type_created', table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_user_settings_key'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_category'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_category'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_search_history_query_type'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_query_text'), table_name='search_history')
    op.drop_index(op.f('ix_search_history_id'), table_name='search_history')
    op.drop_table('search_history')
    op.drop_index(op.f('ix_directories_path'), table_name='directories')
    op.drop_index(op.f('ix_directories_name'), table_name='directories')
    op.drop_index(op.f('ix_directories_id'), table_name='directories')
    op.drop_table('directories')
    # ### end Alembic commands ###